;;; jungle-theme.el --- jungle theme with Emacs theme engine

;; Author: Azer Koçulu <azer@roadbeats.com>
;; URL: https://github.com/azer/jungle-theme
;; Package-Version:
;; Version: 1.0

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:

(deftheme jungle
  "jungle theme")

(custom-theme-set-faces
 'jungle

 '(default ((t (:background "#1B1D1E" :foreground "#F8F8F2"))))
 '(cursor ((t (:background "#F8F8F0"))))

 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:weight bold :slant italic))))
 '(custom-face-tag ((t (:foreground "#66D9EF" :weight bold))))
 '(custom-state ((t (:foreground "#A6E22E"))))
 '(elfeed-search-date-face ((t (:foreground "#465457"))))
 '(elfeed-search-feed-face ((t (:foreground "#66D9EF"))))
 '(elfeed-search-tag-face ((t (:foreground "#A6E22E" :weight bold))))
 '(elfeed-search-title-face ((t (:foreground "#F8F8F2"))))
 '(italic ((t (:slant italic))))
 '(region ((t (:background "#111"))))
 '(underline ((t (:underline t))))
 '(css-selector ((t (:foreground "#F92672"))))
 '(css-property ((t (:foreground "#66D9EF"))))
 '(diff-added ((t (:foreground "#A6E22E" :weight bold))))
 '(diff-context ((t (:foreground "#F8F8F2"))))
 '(diff-file-header ((t (:foreground "#66D9EF" :background nil))))
 '(diff-indicator-added ((t (:foreground "#A6E22E"))))
 '(diff-indicator-removed ((t (:foreground "#F92672"))))
 '(diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
 '(diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
 '(diff-removed ((t (:foreground "#F92672" :weight bold))))
 '(escape-glyph ((t (:foreground "#E6DB74"))))
 '(minibuffer-prompt ((t (:foreground "#66D9EF"))))
 '(mode-line ((t (:foreground "#F8F8F2" :background "#000000"
                  :box (:line-width 1 :color "#000000" :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground nil :background "#000000" :weight semi-bold))))
 '(mode-line-inactive ((t (:foreground "#BCBCBC" :background "#000000"
                           ':box (:line-width 1 :color "#232526")))))
 '(mode-line-mousable ((t (:foreground "#BCBCBC" :background "#000000"))))
 '(mode-line-mousable-minor-mode ((t (:foreground "#BCBCBC" :background "#000000"))))
 '(font-lock-builtin-face ((t (:foreground "#66ff66"))))
 '(font-lock-comment-face ((t (:foreground "#465457" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#465457" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-face ((t (:foreground "#E6DB74" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#FFbb88" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#66D9EF"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "#66D977"))))
 '(font-lock-variable-name-face ((t (:foreground "#cc9955"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" ':background "#333333"))))
 '(fringe ((t (:background "#1B1D1E" :foreground "#333"))))
 '(highlight ((t (:foreground "#000000" :background "#C4BE89"))))
 '(hl-line ((t (:background "#212729"))))
 '(icompletep-choices ((t (:foreground "#F92672"))))
 '(icompletep-determined ((t (:foreground "#A6E22E"))))
 '(icompletep-keys ((t (:foreground "#F92672"))))
 '(icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
 '(ido-first-match ((t (:foreground "#A6E22E" :weight bold))))
 '(ido-only-match ((t (:foreground "#A6E22E"))))
 '(ido-subdir ((t (:foreground "#FD971F"))))
 '(isearch ((t (:foreground "#C4BE89" :background "#000000"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
 '(lazy-highlight ((t (:foreground "#465457" :background "#000000"))))
 '(markdown-italic-face ((t (:slant italic))))
 '(markdown-bold-face ((t (:weight bold))))
 '(markdown-header-face ((t (:weight normal))))
 '(markdown-header-face-1 ((t (:foreground "#66D9EF"))))
 '(markdown-header-face-2 ((t (:foreground "#F92672"))))
 '(markdown-header-face-3 ((t (:foreground "#A6E22E"))))
 '(markdown-header-face-4 ((t (:foreground "#AE81FF"))))
 '(markdown-header-face-5 ((t (:foreground "#E6DB74"))))
 '(markdown-header-face-6 ((t (:foreground "#66D9EF"))))
 '(markdown-inline-code-face ((t (:foreground "#66D9EF"))))
 '(markdown-list-face ((t (:foreground "#A6E22E"))))
 '(markdown-blockquote-face ((t (:slant italic))))
 '(markdown-pre-face ((t (:foreground "#AE81FF"))))
 '(markdown-link-face ((t (:foreground "#66D9EF"))))
 '(markdown-reference-face ((t (:foreground "#66D9EF"))))
 '(markdown-url-face ((t (:foreground "#E6DB74"))))
 '(markdown-link-title-face ((t (:foreground "#F92672"))))
 '(markdown-comment-face ((t (:foreground "#465457"))))
 '(markdown-math-face ((t (:foreground "#AE81FF" :slant italic))))
 '(mumamo-background-chunk-major ((t (:background "#272822"))))
 '(mumamo-background-chunk-submode ((t (:background "#1B1D1E"))))
 '(outline-1 ((t (:foreground "#C4BE89"))))
 '(outline-2 ((t (:foreground "#FD971F"))))
 '(outline-3 ((t (:foreground "#EF5939"))))
 '(outline-4 ((t (:foreground "#F92672"))))
 '(outline-5 ((t (:foreground "#960050"))))
 '(outline-6 ((t (:foreground "#AE81FF"))))
 '(outline-7 ((t (:foreground "#66D9EF"))))
 '(outline-8 ((t (:foreground "#A6E22E"))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit outline-1))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit outline-2))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit outline-3))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit outline-4))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit outline-5))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit outline-6))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit outline-7))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit outline-8))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#BCA3A3"))))
 '(secondary-selection ((t (:background "#272822"))))
 '(shadow ((t (:foreground "#465457"))))
 '(show-paren-match-face ((t (:foreground "#000000" :background "#FD971F"))))
 '(show-paren-mismatch-face ((t (:foreground "#960050" :background "#1E0010"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#EF5939"))))
 '(undo-tree-visualizer-default-face ((t (:inherit shadow))))
 '(undo-tree-visualizer-register-face ((t (:foreground "E6DB74"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#66D9EF"))))
 '(widget-inactive-face ((t (:background "#ff0000"))))
 '(woman-addition ((t (:foreground "#AE81FF"))))
 '(woman-bold ((t (:foreground "#F92672"))))
 '(woman-italic ((t (:foreground "#A6E22E"))))
 '(woman-unknown ((t (:foreground "#66D9EF"))))

 '(vertical-border ((t (:foreground "#1B1D1E"))))
 '(linum-relative-current-face ((t (:foreground "#c56ec3" :background "#1b1d1e"))))

 '(helm-bookmark-file ((t (:foreground "#b2b2b2"))))
 '(helm-bookmark-gnus ((t (:foreground "#c56ec3"))))
 '(helm-bookmark-info ((t (:foreground "#c56ec3"))))
 '(helm-bookmark-man ((t (:foreground "#c56ec3"))))
 '(helm-bookmark-w3m ((t (:foreground "#c56ec3"))))
 '(helm-buffer-directory ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-file ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-not-saved ((t (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-buffer-process ((t (:foreground "#4f97d7" :background "#292b2e"))))
 '(helm-buffer-saved-out ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-size ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-candidate-number ((t (:background "#292b2e" :foreground "#4f97d7" :inherit bold))))
 '(helm-ff-directory ((t (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(helm-ff-dotted-directory ((t (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((t (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(helm-ff-executable ((t (:foreground "#86dc2f" :background "#292b2e" :weight normal))))
 '(helm-ff-file ((t (:foreground "#b2b2b2" :background "#292b2e" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#f2241f" :background "#292b2e" :inherit bold))))
 '(helm-ff-prefix ((t (:foreground "#292b2e" :background "#4f97d7" :weight normal))))
 '(helm-ff-symlink ((t (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(helm-grep-cmd-line ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-file ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-finish ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-lineno ((t (:foreground "#ce537a" :background "#292b2e" :inherit bold))))
 '(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((t (:foreground "#b2b2b2" :background "#292b2e" :underline nil :box nil))))
 '(helm-header-line-left-margin ((t (:foreground "#4f97d7" :background "#000"))))
 '(helm-match ((t (:background "#293239" :foreground "#4f97d7"1))))
 '(helm-match-item ((t (:background "#293239" :foreground "#4f97d7"1))))
 '(helm-moccur-buffer ((t (:foreground "#7590db" :background "#292b2e"))))
 '(helm-selection ((t (:background "#444155"))))
 '(helm-selection-line ((t (:background "#212026"))))
 '(helm-separator ((t (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-source-header ((t (:background "#c56ec3" :foreground "#292b2e" :inherit bold))))
 '(helm-time-zone-current ((t (:foreground "#4f97d7" :background "#292b2e"))))
 '(helm-time-zone-home ((t (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-visible-mark ((t (:foreground "#4f97d7" :background "#100a14"))))

 ;;;;; org
 '(org-agenda-clocking ((t (:background "#444155" :foreground "#c56ec3"))))
 '(org-agenda-date ((t (:foreground "#7590db" :height 1.0))))
 '(org-agenda-date-today ((t (:foreground "#4f97d7" :inherit bold :height 1.0))))
 '(org-agenda-date-weekend ((t (:inherit bold :foreground "#7590db"))))
 '(org-agenda-done ((t (:foreground "#86dc2f" :height 1.0))))
 '(org-agenda-structure ((t (:inherit bold :foreground "#c56ec3"))))
 '(org-block ((t (:background "#2f2b33" :foreground "#cbc1d5"))))
 '(org-block-begin-line ((t (:background "#373040" :foreground "#827591"))))
 '(org-block-end-line ((t (:background "#373040" :foreground "#827591"))))
 '(org-clock-overlay ((t (:foreground "#c56ec3"))))
 '(org-code ((t (:foreground "#28def0"))))
 '(org-column ((t (:background "#444155"))))
 '(org-column-title ((t (:background "#444155"))))
 '(org-date ((t (:underline t :foreground "#7590db"))))
 '(org-date-selected ((t (:background "#bc6ec5" :foreground "#292b2e"))))
 '(org-document-info-keyword ((t (:foreground "#958766"))))
 '(org-document-title ((t (:foreground "#bc6ec5" :inherit bold :height 1.0 :underline t))))
 '(org-done ((t (:foreground "#11aa55" :inherit bold :background nil))))
 '(org-ellipsis ((t (:foreground "#4f97d7"))))
 '(org-footnote  ((t (:underline t :foreground "#b2b2b2"))))
 '(org-hide ((t (:foreground "#1B1D1E"))))
 '(org-kbd ((t (:inherit region :foreground "#b2b2b2" :box (:line-width 1 :style released-button)))))
 '(org-level-1 ((t (:inherit bold :foreground "#4f97d7" :height 1.0))))
 '(org-level-2 ((t (:inherit bold :foreground "#2d9574" :height 1.0))))
 '(org-level-3 ((t (:bold nil :foreground "#998844" :height 1.0))))
 '(org-level-4 ((t (:bold nil :foreground "#b1951d"))))
 '(org-level-5 ((t (:bold nil :foreground "#4f97d7"))))
 '(org-level-6 ((t (:bold nil :foreground "#2d9574"))))
 '(org-level-7 ((t (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((t (:bold nil :foreground "#b1951d"))))
 '(org-link ((t (:underline t :foreground "#2aa1ae"))))
 '(org-meta-line ((t (:foreground "#9f8766"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#e0211d"))))
 '(org-priority ((t (:foreground "#dc752f" :inherit bold))))
 '(org-quote ((t (:inherit org-block :slant italic))))
 '(org-scheduled ((t (:foreground "#c56ec3"))))
 '(org-scheduled-today ((t (:foreground "#bc6ec5"))))
 '(org-sexp-date ((t (:foreground "#b2b2b2"))))
 '(org-special-keyword ((t (:foreground "#bc6ec5"))))
 '(org-table ((t (:foreground "#b2b2b2" :background nil))))
 '(org-time-grid ((t (:foreground "#2d9574"))))
 '(org-todo ((t (:foreground "#cc4422" :inherit bold :background nil))))
 '(org-verbatim ((t (:foreground "#4f97d7"))))
 '(org-verse ((t (:inherit org-block :slant italic))))
 '(org-warning ((t (:foreground "#e0211d"))))

 ;; ac-mode
 '(ac-completion-face ((t (:background "#34323e" :foreground "#9a9aba"))))

 ;; company
 '(company-echo-common ((t (:background "#b2b2b2" :foreground "#fff"))))
 '(company-preview ((t (:background "#34323e" :foreground "#9a9aba"))))
 '(company-preview-common ((t (:background "#34323e" :foreground "#b2b2b2"))))
 '(company-preview-search ((t (:inherit match))))
 '(company-scrollbar-bg ((t (:background "#333"))))
 '(company-scrollbar-fg ((t (:background "#111"))))
 '(company-template-field ((t (:inherit region))))
 '(company-tooltip ((t (:background "#111111" :foreground "#888"))))
 '(company-tooltip-annotation ((t (:foreground "#fff"))))
 '(company-tooltip-common ((t (:background "#111" :foreground "#cff"))))
 '(company-tooltip-common-selection ((t (:foreground "#fff"))))
 '(company-tooltip-mouse ((t (:inherit highlight))))
 '(company-tooltip-search ((t (:inherit match))))
 '(company-tooltip-selection ((t (:background "#cc3388" :foreground "#fff" :weight bold))))
)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'jungle)

;;; molokai-theme.el ends here
